org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.aapt2FromMavenOverride=/root/Android/Sdk/build-tools/36.0.0/aapt2
org.gradle.jvmargs=-Xmx1536m
org.gradle.daemon=false
